### ISSUE TITLE
how to use it

### ISSUE THREAD

**Issue by abe520** [githubfzq/joplin2obsidian#1]
![Snipaste_2022-07-01_12-42-55](https://user-images.githubusercontent.com/9929511/176824921-06b3765a-66eb-4c48-a38c-e3fd8b40dd6b.png)
something wrong

**Comment by githubfzq** [comment]
New version is provided:
changes:

#2 fix path not found error.
#3 add usage

**Comment by abe520** [comment]
windows:
````
cd joplin2obsidian
python -m venv \j2o\venv
\j2o\venv\Scripts\activate.bat
pip install poetry 
poetry install

poetry run python main.py -s 1 -d 2
````
